// GENERATED by tool/build-tokens.mjs — DO NOT EDIT BY HAND.
//
// Source: tokens/src/color.tokens.json
// Regenerate: node tool/build-tokens.mjs   (from the repo root)
//
// Dart cannot evaluate oklch, so every step is baked to sRGB here. Conversion
// uses chroma-reduction gamut mapping rather than clipping: clipping shifts hue,
// which would break the promise that every app's ramp differs only in H. A few
// steps therefore sit at slightly lower chroma than the source asks for.
//
// See decisions/0007-token-source-format.md.

import 'dart:ui' show Color;

/// One app's accent ramp. Mirrors --brand-050 … --brand-900 plus --brand-wash.
class SkBrandRamp {
  const SkBrandRamp({
    required this.s100,
    required this.s200,
    required this.s300,
    required this.s400,
    required this.s500,
    required this.s600,
    required this.s700,
    required this.s800,
    required this.s900,
    required this.s050,
    required this.wash,
  });

  final Color s100;
  final Color s200;
  final Color s300;
  final Color s400;
  final Color s500;
  final Color s600;
  final Color s700;
  final Color s800;
  final Color s900;
  final Color s050;
  final Color wash;
}

/// The accent ramp for each app. Adding an app means adding a hue to
/// tokens/src/color.tokens.json and re-running the build — never hand-typing
/// colours.
class SkBrandRamps {
  const SkBrandRamps._();

  /// oklch(L C 8) — SeaKim house — decks, cross-product surfaces
  static const SkBrandRamp brick = SkBrandRamp(
    s100: Color(0xFFFDD6DB),
    s200: Color(0xFFF7B7C1),
    s300: Color(0xFFF6A3B1),
    s400: Color(0xFFE98095),
    s500: Color(0xFFD1647C),
    s600: Color(0xFFB64B65),
    s700: Color(0xFF8D364B),
    s800: Color(0xFF652333),
    s900: Color(0xFF3F121D),
    s050: Color(0xFFFFECEF),
    wash: Color(0xFF31151B),
  );

  /// oklch(L C 245) — Voyage — travel planning and booking
  static const SkBrandRamp sea = SkBrandRamp(
    s100: Color(0xFFC9E5FE),
    s200: Color(0xFFA2D0F9),
    s300: Color(0xFF86C5FA),
    s400: Color(0xFF56ACF0),
    s500: Color(0xFF3093DB),
    s600: Color(0xFF037AC0),
    s700: Color(0xFF005C94),
    s800: Color(0xFF00406A),
    s900: Color(0xFF002642),
    s050: Color(0xFFE7F4FF),
    wash: Color(0xFF0A2133),
  );

  /// oklch(L C 145) — Bench — fantasy sport
  static const SkBrandRamp turf = SkBrandRamp(
    s100: Color(0xFFD0EACF),
    s200: Color(0xFFADD8AD),
    s300: Color(0xFF95CF96),
    s400: Color(0xFF6DBA70),
    s500: Color(0xFF4EA253),
    s600: Color(0xFF34893C),
    s700: Color(0xFF226929),
    s800: Color(0xFF14491A),
    s900: Color(0xFF082C0C),
    s050: Color(0xFFE9F6E9),
    wash: Color(0xFF102511),
  );

  /// oklch(L C 320) — Reserved for app three
  static const SkBrandRamp plum = SkBrandRamp(
    s100: Color(0xFFEFD8F4),
    s200: Color(0xFFE1BBE9),
    s300: Color(0xFFDBA9E6),
    s400: Color(0xFFC889D7),
    s500: Color(0xFFB16EC0),
    s600: Color(0xFF9856A7),
    s700: Color(0xFF753E81),
    s800: Color(0xFF522A5C),
    s900: Color(0xFF321739),
    s050: Color(0xFFF9EDFB),
    wash: Color(0xFF29182C),
  );
}

/// The warm achromatic spine. Never per-app.
class SkStone {
  const SkStone._();

  static const Color s0 = Color(0xFFFFFFFF);
  static const Color s50 = Color(0xFFFAF9F7);
  static const Color s100 = Color(0xFFF0EFEC);
  static const Color s200 = Color(0xFFE0DEDA);
  static const Color s300 = Color(0xFFC6C3BD);
  static const Color s400 = Color(0xFFA09C95);
  static const Color s500 = Color(0xFF7C7873);
  static const Color s600 = Color(0xFF5C5955);
  static const Color s700 = Color(0xFF413F3C);
  static const Color s800 = Color(0xFF2B2A27);
  static const Color s850 = Color(0xFF211F1D);
  static const Color s900 = Color(0xFF181614);
  static const Color s950 = Color(0xFF0F0E0D);
}

/// Status ramps. The 400 step is tuned for dark surfaces, 500 for light.
class SkStatusPalette {
  const SkStatusPalette._();

  static const Color success400 = Color(0xFF6BD185);
  static const Color success500 = Color(0xFF2E9E52);
  static const Color warning400 = Color(0xFFEEBC4A);
  static const Color warning500 = Color(0xFFCB8900);
  static const Color danger400 = Color(0xFFF67972);
  static const Color danger500 = Color(0xFFD94543);
  static const Color info400 = Color(0xFF62BBF5);
  static const Color info500 = Color(0xFF177DD1);

  static const Color successSubtleDark = Color(0xFF17351F);
  static const Color warningSubtleDark = Color(0xFF3C2A07);
  static const Color dangerSubtleDark = Color(0xFF491F1D);
  static const Color infoSubtleDark = Color(0xFF133047);

  static const Color successTextLight = Color(0xFF067132);
  static const Color warningTextLight = Color(0xFF856300);
  static const Color dangerTextLight = Color(0xFFB33736);
  static const Color infoTextLight = Color(0xFF006A9E);

  static const Color successSubtleLight = Color(0xFFE4F8E7);
  static const Color warningSubtleLight = Color(0xFFFEF0D4);
  static const Color dangerSubtleLight = Color(0xFFFFEDEB);
  static const Color infoSubtleLight = Color(0xFFE6F4FF);
}

/// Values tuned by eye rather than derived — theme-specific near-blacks,
/// borders, and scrims.
class SkRawColors {
  const SkRawColors._();

  static const Color surfaceSunkenDark = Color(0xFF0A0908);
  static const Color surfaceShimmerDark = Color(0xFF1E1B18);
  static const Color surfaceShimmerLight = Color(0xFFE3E1DD);
  static const Color textPrimaryDark = Color(0xFFF5F3F0);
  static const Color borderSubtleDark = Color(0xFF2A2724);
  static const Color borderDefaultDark = Color(0xFF383431);
  static const Color borderStrongDark = Color(0xFF4C4844);
  static const Color borderDisabledDark = Color(0xFF2E2B28);
  static const Color onDangerDark = Color(0xFFFDF6F4);
  static const Color scrimDark = Color(0xAD000000);
  static const Color scrimLight = Color(0x662B2A27);
}

/// Categorical series for charts. Equal lightness and chroma, hue only, so
/// no series reads as louder than its neighbour.
class SkChartPalette {
  const SkChartPalette._();

  static const Color series1 = Color(0xFF4FA6E9);
  static const Color series2 = Color(0xFF67B36A);
  static const Color series3 = Color(0xFFDC8748);
  static const Color series4 = Color(0xFFC282D0);
  static const Color series5 = Color(0xFF00B5B5);
  static const Color series6 = Color(0xFFE47C75);

  /// Assign in this order. A series keeps its colour across every view it
  /// appears in, so never reorder per chart.
  static const List<Color> ordered = <Color>[
    series1, series2, series3, series4, series5, series6,
  ];
}

/// Sequential ramp for magnitude — heatmaps, rank grids, choropleths.
///
/// Per-theme rather than one ramp inverted: each direction is validated on its
/// own surface, per decision 0015.
class SkChartSeq {
  const SkChartSeq({
    required this.s1,
    required this.s2,
    required this.s3,
    required this.s4,
    required this.inkFlip,
  });

  final Color s1;
  final Color s2;
  final Color s3;
  final Color s4;

  /// Step at which label ink flips to the inverse text colour.
  final int inkFlip;

  /// Step by 1-based index. Values outside 1–4 clamp to the ends.
  Color step(int i) => switch (i.clamp(1, 4)) {
        1 => s1,
        2 => s2,
        3 => s3,
        _ => s4,
      };

  /// Ascends into darkness.
  static const SkChartSeq light = SkChartSeq(
    s1: Color(0xFFDDE8FF),
    s2: Color(0xFFA8C4FF),
    s3: Color(0xFF6F95EB),
    s4: Color(0xFF3D63BE),
    inkFlip: 4,
  );

  /// Ascends into lightness.
  static const SkChartSeq dark = SkChartSeq(
    s1: Color(0xFF26365C),
    s2: Color(0xFF3C5898),
    s3: Color(0xFF567CD3),
    s4: Color(0xFF82A8FD),
    inkFlip: 3,
  );
}
