// Generates lib/src/tokens/sk_icons.g.dart from tool/phosphor_codepoints.json.
//
//     dart run tool/gen_icons.dart
//
// Same contract as gen_tokens.dart: the JSON is the checked-in source of truth
// and the .g.dart is disposable — never hand-edit the generated file.
//
// The JSON was extracted from the Phosphor icon fonts shipped in
// assets/icons/ (MIT, see assets/icons/LICENSE-phosphor.txt). Regenerate it
// only when those fonts are updated, and keep the two in step: a code point
// here that the bundled font does not contain renders as tofu.
//
// Why const IconData rather than bare code points: Flutter's
// `--tree-shake-icons` pass only recognises const IconData instances. Resolving
// a code point to an IconData at render time silently disables tree shaking and
// ships all four fonts (~2 MB) whole. The verbosity below is the price of that,
// and it costs nothing because the file is generated.

import 'dart:convert';
import 'dart:io';

const String _out = 'lib/src/tokens/sk_icons.g.dart';
const String _src = 'tool/phosphor_codepoints.json';

void main() {
  final File input = File(_src);
  if (!input.existsSync()) {
    stderr.writeln('missing $_src — run from the flutter/ package root');
    exitCode = 1;
    return;
  }

  final Map<String, dynamic> raw =
      jsonDecode(input.readAsStringSync()) as Map<String, dynamic>;

  final List<String> names = raw.keys.toList()..sort();
  final List<String> patched = <String>[];

  final StringBuffer b = StringBuffer()
    ..writeln('// GENERATED BY tool/gen_icons.dart — DO NOT EDIT BY HAND.')
    ..writeln('//')
    ..writeln('// Source: $_src')
    ..writeln('// Fonts:  assets/icons/Phosphor-{Regular,Bold,Fill,Duotone}.ttf')
    ..writeln('//         Phosphor Icons, MIT — assets/icons/LICENSE-phosphor.txt')
    ..writeln('//')
    ..writeln('// Regenerate: dart run tool/gen_icons.dart')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln("import 'sk_glyph.dart';")
    ..writeln()
    ..writeln('/// Every Phosphor glyph, in the four weights SeaKim draws.')
    ..writeln('///')
    ..writeln('/// Pass one to [SkIcon] — it picks the weight:')
    ..writeln('///')
    ..writeln('///     SkIcon(SkIcons.mapPin)')
    ..writeln('class SkIcons {')
    ..writeln('  const SkIcons._();')
    ..writeln();

  for (final String name in names) {
    final Map<String, dynamic> w = (raw[name] as Map<String, dynamic>);

    // A handful of glyphs are absent from one weight's font. Fall back rather
    // than drop the icon: a slightly heavier glyph beats a missing one, and a
    // duotone fallback simply draws flat.
    final String? regular = w['regular'] as String?;
    final String? bold = w['bold'] as String?;
    final String? fill = w['fill'] as String?;
    final String? duotone = w['duotone'] as String?;
    final String? base = regular ?? bold ?? fill ?? duotone;
    if (base == null) {
      stderr.writeln('skipping $name — no code point in any weight');
      continue;
    }
    final String rTone = regular ?? base;
    final String bTone = bold ?? base;
    final String fTone = fill ?? base;
    final String dTone = duotone ?? base;
    final String dSec = (w['duotoneSecondary'] as String?) ?? dTone;

    if (regular == null || bold == null || fill == null || duotone == null) {
      patched.add(name);
    }

    b
      ..writeln('  static const SkGlyph $name = SkGlyph(')
      ..writeln('    regular: ${_icon(rTone, 'SkIconFont.regular')},')
      ..writeln('    bold: ${_icon(bTone, 'SkIconFont.bold')},')
      ..writeln('    fill: ${_icon(fTone, 'SkIconFont.fill')},')
      ..writeln('    duotone: ${_icon(dTone, 'SkIconFont.duotone')},')
      ..writeln('    duotoneSecondary: ${_icon(dSec, 'SkIconFont.duotone')},')
      ..writeln('  );');
  }

  b.writeln('}');

  File(_out)
    ..createSync(recursive: true)
    ..writeAsStringSync(b.toString());

  stdout.writeln('wrote $_out — ${names.length} glyphs');
  if (patched.isNotEmpty) {
    stdout.writeln(
        '${patched.length} glyph(s) missing a weight, filled by fallback: '
        '${patched.join(', ')}');
  }
}

String _icon(String codePoint, String family) =>
    'IconData($codePoint, fontFamily: $family, fontPackage: skIconFontPackage)';
