// Generates lib/src/tokens/sk_icons.g.dart from tool/phosphor_codepoints.json.
//
//     dart run tool/gen_icons.dart
//
// Same contract as gen_tokens.dart: the JSON is the checked-in source of truth
// and the .g.dart is disposable — never hand-edit the generated file.
//
// The JSON was extracted from the Phosphor icon fonts shipped in
// assets/icons/ (MIT, see assets/icons/LICENSE-phosphor.txt). Regenerate it
// only when those fonts are updated, and keep the two in step: a code point
// here that the bundled font does not contain renders as tofu.
//
// Why const IconData rather than bare code points: Flutter's
// `--tree-shake-icons` pass only recognises const IconData instances. Resolving
// a code point to an IconData at render time silently disables tree shaking and
// ships all four fonts (~2 MB) whole. The verbosity below is the price of that,
// and it costs nothing because the file is generated.

import 'dart:convert';
import 'dart:io';

const String _out = 'lib/src/tokens/sk_icons.g.dart';
const String _src = 'tool/phosphor_codepoints.json';

void main() {
  final File input = File(_src);
  if (!input.existsSync()) {
    stderr.writeln('missing $_src — run from the flutter/ package root');
    exitCode = 1;
    return;
  }

  final Map<String, dynamic> raw =
      jsonDecode(input.readAsStringSync()) as Map<String, dynamic>;

  final List<String> names = raw.keys.toList()..sort();
  final List<String> patched = <String>[];

  final StringBuffer b = StringBuffer()
    ..writeln('// GENERATED BY tool/gen_icons.dart — DO NOT EDIT BY HAND.')
    ..writeln('//')
    ..writeln('// Source: $_src')
    ..writeln('// Fonts:  assets/icons/Phosphor-{Regular,Bold,Fill,Duotone}.ttf')
    ..writeln('//         Phosphor Icons, MIT — assets/icons/LICENSE-phosphor.txt')
    ..writeln('//')
    ..writeln('// Regenerate: dart run tool/gen_icons.dart')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln("import 'sk_glyph.dart';")
    ..writeln()
    ..writeln('/// Every Phosphor glyph, in the four weights SeaKim draws.')
    ..writeln('///')
    ..writeln('/// Pass one to [SkIcon] — it picks the weight:')
    ..writeln('///')
    ..writeln('///     SkIcon(SkIcons.mapPin)')
    ..writeln('class SkIcons {')
    ..writeln('  const SkIcons._();')
    ..writeln();

  for (final String name in names) {
    final Map<String, dynamic> w = (raw[name] as Map<String, dynamic>);

    // A handful of glyphs are absent from one weight's font. Fall back rather
    // than drop the icon — but a code point only exists in the font it came
    // from, so the fallback has to carry that weight's FAMILY too. Pairing a
    // borrowed code point with the requested family renders tofu, and makes
    // `--tree-shake-icons` abort the build outright ("Codepoint N not found in
    // font"), which is how this was caught.
    final Map<String, String?> byWeight = <String, String?>{
      'SkIconFont.regular': w['regular'] as String?,
      'SkIconFont.bold': w['bold'] as String?,
      'SkIconFont.fill': w['fill'] as String?,
      'SkIconFont.duotone': w['duotone'] as String?,
    };

    MapEntry<String, String>? base;
    for (final MapEntry<String, String?> e in byWeight.entries) {
      if (e.value != null) {
        base = MapEntry<String, String>(e.key, e.value!);
        break;
      }
    }
    if (base == null) {
      stderr.writeln('skipping $name — no code point in any weight');
      continue;
    }
    if (byWeight.values.any((String? v) => v == null)) patched.add(name);

    /// The (code point, family) pair for one weight, or the nearest weight that
    /// actually has the glyph.
    String resolve(String family) {
      final String? own = byWeight[family];
      return own != null ? _icon(own, family) : _icon(base!.value, base.key);
    }

    // The duotone backdrop is a second glyph in the duotone font; if it is
    // absent, draw the foreground alone rather than a mismatched pair.
    final String? dSec = w['duotoneSecondary'] as String?;
    final String duotoneField = resolve('SkIconFont.duotone');
    final String secondaryField = (dSec != null && byWeight['SkIconFont.duotone'] != null)
        ? _icon(dSec, 'SkIconFont.duotone')
        : duotoneField;

    b
      ..writeln('  static const SkGlyph $name = SkGlyph(')
      ..writeln('    regular: ${resolve('SkIconFont.regular')},')
      ..writeln('    bold: ${resolve('SkIconFont.bold')},')
      ..writeln('    fill: ${resolve('SkIconFont.fill')},')
      ..writeln('    duotone: $duotoneField,')
      ..writeln('    duotoneSecondary: $secondaryField,')
      ..writeln('  );');
  }

  b.writeln('}');

  File(_out)
    ..createSync(recursive: true)
    ..writeAsStringSync(b.toString());

  stdout.writeln('wrote $_out — ${names.length} glyphs');
  if (patched.isNotEmpty) {
    stdout.writeln(
        '${patched.length} glyph(s) missing a weight, filled by fallback: '
        '${patched.join(', ')}');
  }
}

String _icon(String codePoint, String family) =>
    'IconData($codePoint, fontFamily: $family, fontPackage: skIconFontPackage)';
